version: "4.23.0"
services:
  spring-el-sol-image:
    image: el-sol
    container_name: el-sol-container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - el-sol-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: el_sol
      MYSQL_USER: dracukeo
      MYSQL_PASSWORD: 21312
    ports:
      - "3307:3306"
    networks:
      - el-sol-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  el-sol-network:
volumes:
  mysql-volume: